// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $Account_IframeMyAccount from "./islands/Account/IframeMyAccount.tsx";
import * as $Account_LoginButtonIframe from "./islands/Account/LoginButtonIframe.tsx";
import * as $Account_LoginButtonIframeMobile from "./islands/Account/LoginButtonIframeMobile.tsx";
import * as $Account_LoginButtonIframeMobileHeader from "./islands/Account/LoginButtonIframeMobileHeader.tsx";
import * as $Account_UserName from "./islands/Account/UserName.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $Content_ButtonCopy from "./islands/Content/ButtonCopy.tsx";
import * as $Content_CategorySEOContent from "./islands/Content/CategorySEOContent.tsx";
import * as $Content_Cupons_CopyCupom from "./islands/Content/Cupons/CopyCupom.tsx";
import * as $Content_Cupons_ModalConditional from "./islands/Content/Cupons/ModalConditional.tsx";
import * as $DrawerInstitucional from "./islands/DrawerInstitucional.tsx";
import * as $FiltersSelected from "./islands/FiltersSelected.tsx";
import * as $Header_Bonifiq from "./islands/Header/Bonifiq.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_SearchBarSuggestion from "./islands/Header/SearchBarSuggestion.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $Header_Wishlist from "./islands/Header/Wishlist.tsx";
import * as $LPs_ButtonMenuMarcas from "./islands/LPs/ButtonMenuMarcas.tsx";
import * as $Live_Button from "./islands/Live/Button.tsx";
import * as $Modal_Button from "./islands/Modal/Button.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $Oscar_Buttons from "./islands/Oscar/Buttons.tsx";
import * as $Oscar_Drawers from "./islands/Oscar/Drawers.tsx";
import * as $Oscar_LoginButton from "./islands/Oscar/LoginButton.tsx";
import * as $Oscar_ScrollableContainer from "./islands/Oscar/ScrollableContainer.tsx";
import * as $Oscar_SearchBar from "./islands/Oscar/SearchBar.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $Product_BuyBox from "./islands/Product/BuyBox.tsx";
import * as $Product_Installments from "./islands/Product/Installments.tsx";
import * as $Product_ProductVisited from "./islands/Product/ProductVisited.tsx";
import * as $Product_SellerName from "./islands/Product/SellerName.tsx";
import * as $ProductImageSlider from "./islands/ProductImageSlider.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductName from "./islands/ProductName.tsx";
import * as $ProductPrice from "./islands/ProductPrice.tsx";
import * as $ProductVariant from "./islands/ProductVariant.tsx";
import * as $Redirect from "./islands/Redirect.tsx";
import * as $Search_FiltersSelected from "./islands/Search/FiltersSelected.tsx";
import * as $Search_PriceRange from "./islands/Search/PriceRange.tsx";
import * as $Search_ProductGallery from "./islands/Search/ProductGallery.tsx";
import * as $Search_ViewCardsButton from "./islands/Search/ViewCardsButton.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Stopwatch from "./islands/Stopwatch.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
  },
  islands: {
    "./islands/Account/IframeMyAccount.tsx": $Account_IframeMyAccount,
    "./islands/Account/LoginButtonIframe.tsx": $Account_LoginButtonIframe,
    "./islands/Account/LoginButtonIframeMobile.tsx":
      $Account_LoginButtonIframeMobile,
    "./islands/Account/LoginButtonIframeMobileHeader.tsx":
      $Account_LoginButtonIframeMobileHeader,
    "./islands/Account/UserName.tsx": $Account_UserName,
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/Content/ButtonCopy.tsx": $Content_ButtonCopy,
    "./islands/Content/CategorySEOContent.tsx": $Content_CategorySEOContent,
    "./islands/Content/Cupons/CopyCupom.tsx": $Content_Cupons_CopyCupom,
    "./islands/Content/Cupons/ModalConditional.tsx":
      $Content_Cupons_ModalConditional,
    "./islands/DrawerInstitucional.tsx": $DrawerInstitucional,
    "./islands/FiltersSelected.tsx": $FiltersSelected,
    "./islands/Header/Bonifiq.tsx": $Header_Bonifiq,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/SearchBarSuggestion.tsx": $Header_SearchBarSuggestion,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/Header/Wishlist.tsx": $Header_Wishlist,
    "./islands/LPs/ButtonMenuMarcas.tsx": $LPs_ButtonMenuMarcas,
    "./islands/Live/Button.tsx": $Live_Button,
    "./islands/Modal/Button.tsx": $Modal_Button,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/Oscar/Buttons.tsx": $Oscar_Buttons,
    "./islands/Oscar/Drawers.tsx": $Oscar_Drawers,
    "./islands/Oscar/LoginButton.tsx": $Oscar_LoginButton,
    "./islands/Oscar/ScrollableContainer.tsx": $Oscar_ScrollableContainer,
    "./islands/Oscar/SearchBar.tsx": $Oscar_SearchBar,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/Product/BuyBox.tsx": $Product_BuyBox,
    "./islands/Product/Installments.tsx": $Product_Installments,
    "./islands/Product/ProductVisited.tsx": $Product_ProductVisited,
    "./islands/Product/SellerName.tsx": $Product_SellerName,
    "./islands/ProductImageSlider.tsx": $ProductImageSlider,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductName.tsx": $ProductName,
    "./islands/ProductPrice.tsx": $ProductPrice,
    "./islands/ProductVariant.tsx": $ProductVariant,
    "./islands/Redirect.tsx": $Redirect,
    "./islands/Search/FiltersSelected.tsx": $Search_FiltersSelected,
    "./islands/Search/PriceRange.tsx": $Search_PriceRange,
    "./islands/Search/ProductGallery.tsx": $Search_ProductGallery,
    "./islands/Search/ViewCardsButton.tsx": $Search_ViewCardsButton,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Stopwatch.tsx": $Stopwatch,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
