// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$2 from "./loaders/Pix/showPix.ts";
import * as $$$3 from "./loaders/Trustvox/productDetailsPage.ts";
import * as $$$$$$0 from "./sections/Account/IframeMyAccount.tsx";
import * as $$$$$$1 from "./sections/Animation/Animation.tsx";
import * as $$$$$$2 from "./sections/BonifiQ/HeaderBonifiq.tsx";
import * as $$$$$$3 from "./sections/BonifiQ/ScriptBonifiq.tsx";
import * as $$$$$$4 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$5 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$6 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$7 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$10 from "./sections/Category/CategoryGridMatcher.tsx";
import * as $$$$$$11 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$12 from "./sections/Category/CategorySEO.tsx";
import * as $$$$$$13 from "./sections/Category/ChooseYourNumber.tsx";
import * as $$$$$$14 from "./sections/Content/BannerApp.tsx";
import * as $$$$$$15 from "./sections/Content/BenefitContent.tsx";
import * as $$$$$$16 from "./sections/Content/Benefits.tsx";
import * as $$$$$$17 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$18 from "./sections/Content/BonifiQ.tsx";
import * as $$$$$$19 from "./sections/Content/BrandCarousel.tsx";
import * as $$$$$$20 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$21 from "./sections/Content/CardBenefits.tsx";
import * as $$$$$$22 from "./sections/Content/CarouselSlider.tsx";
import * as $$$$$$23 from "./sections/Content/CarrouselInfinit.tsx";
import * as $$$$$$24 from "./sections/Content/CarrouselStores.tsx";
import * as $$$$$$25 from "./sections/Content/ComprePorNumeracao.tsx";
import * as $$$$$$26 from "./sections/Content/ContentBanners.tsx";
import * as $$$$$$27 from "./sections/Content/Cupons/Cupons.tsx";
import * as $$$$$$28 from "./sections/Content/Faq.tsx";
import * as $$$$$$29 from "./sections/Content/Features.tsx";
import * as $$$$$$30 from "./sections/Content/Hero.tsx";
import * as $$$$$$31 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$32 from "./sections/Content/ImageWithModal.tsx";
import * as $$$$$$33 from "./sections/Content/Institutional.tsx";
import * as $$$$$$34 from "./sections/Content/Intro.tsx";
import * as $$$$$$35 from "./sections/Content/Logos.tsx";
import * as $$$$$$36 from "./sections/Content/OurValues.tsx";
import * as $$$$$$37 from "./sections/Content/Partners.tsx";
import * as $$$$$$38 from "./sections/Content/RichText.tsx";
import * as $$$$$$39 from "./sections/Content/SearchTags.tsx";
import * as $$$$$$40 from "./sections/Content/Table.tsx";
import * as $$$$$$41 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$42 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$43 from "./sections/Content/TextWithImageHistory.tsx";
import * as $$$$$$44 from "./sections/Content/UxWriting.tsx";
import * as $$$$$$45 from "./sections/Footer/Footer.tsx";
import * as $$$$$$47 from "./sections/Gallery.tsx";
import * as $$$$$$46 from "./sections/GTM/GTMCustom.tsx";
import * as $$$$$$48 from "./sections/Images/Banner.tsx";
import * as $$$$$$49 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$50 from "./sections/Images/Carousel.tsx";
import * as $$$$$$51 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$52 from "./sections/Images/LowBannerCarrousel.tsx";
import * as $$$$$$53 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$54 from "./sections/Institucionals/BannerGridText.tsx";
import * as $$$$$$55 from "./sections/Institucionals/ButtonNavigation.tsx";
import * as $$$$$$56 from "./sections/Institucionals/CardsStore.tsx";
import * as $$$$$$57 from "./sections/Institucionals/LayoutInstitucional.tsx";
import * as $$$$$$58 from "./sections/Institucionals/Menu.tsx";
import * as $$$$$$59 from "./sections/Institucionals/RichText.tsx";
import * as $$$$$$60 from "./sections/Institucionals/RichTextDefault.tsx";
import * as $$$$$$63 from "./sections/Layout/Container.tsx";
import * as $$$$$$64 from "./sections/Layout/Flex.tsx";
import * as $$$$$$65 from "./sections/Layout/Grid.tsx";
import * as $$$$$$66 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$67 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$68 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$69 from "./sections/Live/LiveMimo.tsx";
import * as $$$$$$61 from "./sections/LPs/Marcas.tsx";
import * as $$$$$$62 from "./sections/LPs/NewsletterPartners.tsx";
import * as $$$$$$95 from "./sections/meta-tag/meta-tag.tsx";
import * as $$$$$$70 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$71 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$72 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$73 from "./sections/Modal/Cookies.tsx";
import * as $$$$$$74 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$75 from "./sections/Oscar/Header.tsx";
import * as $$$$$$76 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$77 from "./sections/Product/NotFound.tsx";
import * as $$$$$$78 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$79 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$80 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$81 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$84 from "./sections/Product/ProductShelffWithImage.tsx";
import * as $$$$$$82 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$83 from "./sections/Product/ProductShelfVisited.tsx";
import * as $$$$$$85 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$86 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$87 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$90 from "./sections/Scripts/Redirect.tsx";
import * as $$$$$$91 from "./sections/Scripts/Scripts.tsx";
import * as $$$$$$88 from "./sections/SEO/HeadingTag.tsx";
import * as $$$$$$89 from "./sections/SEO/SEOPLPV2Custom.tsx";
import * as $$$$$$92 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$93 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$94 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
    "site/loaders/Pix/showPix.ts": $$$2,
    "site/loaders/Trustvox/productDetailsPage.ts": $$$3,
  },
  "sections": {
    "site/sections/Account/IframeMyAccount.tsx": $$$$$$0,
    "site/sections/Animation/Animation.tsx": $$$$$$1,
    "site/sections/BonifiQ/HeaderBonifiq.tsx": $$$$$$2,
    "site/sections/BonifiQ/ScriptBonifiq.tsx": $$$$$$3,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$4,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$5,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$6,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$7,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$8,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$9,
    "site/sections/Category/CategoryGridMatcher.tsx": $$$$$$10,
    "site/sections/Category/CategoryList.tsx": $$$$$$11,
    "site/sections/Category/CategorySEO.tsx": $$$$$$12,
    "site/sections/Category/ChooseYourNumber.tsx": $$$$$$13,
    "site/sections/Content/BannerApp.tsx": $$$$$$14,
    "site/sections/Content/BenefitContent.tsx": $$$$$$15,
    "site/sections/Content/Benefits.tsx": $$$$$$16,
    "site/sections/Content/BlogPosts.tsx": $$$$$$17,
    "site/sections/Content/BonifiQ.tsx": $$$$$$18,
    "site/sections/Content/BrandCarousel.tsx": $$$$$$19,
    "site/sections/Content/CallToAction.tsx": $$$$$$20,
    "site/sections/Content/CardBenefits.tsx": $$$$$$21,
    "site/sections/Content/CarouselSlider.tsx": $$$$$$22,
    "site/sections/Content/CarrouselInfinit.tsx": $$$$$$23,
    "site/sections/Content/CarrouselStores.tsx": $$$$$$24,
    "site/sections/Content/ComprePorNumeracao.tsx": $$$$$$25,
    "site/sections/Content/ContentBanners.tsx": $$$$$$26,
    "site/sections/Content/Cupons/Cupons.tsx": $$$$$$27,
    "site/sections/Content/Faq.tsx": $$$$$$28,
    "site/sections/Content/Features.tsx": $$$$$$29,
    "site/sections/Content/Hero.tsx": $$$$$$30,
    "site/sections/Content/ImageSection.tsx": $$$$$$31,
    "site/sections/Content/ImageWithModal.tsx": $$$$$$32,
    "site/sections/Content/Institutional.tsx": $$$$$$33,
    "site/sections/Content/Intro.tsx": $$$$$$34,
    "site/sections/Content/Logos.tsx": $$$$$$35,
    "site/sections/Content/OurValues.tsx": $$$$$$36,
    "site/sections/Content/Partners.tsx": $$$$$$37,
    "site/sections/Content/RichText.tsx": $$$$$$38,
    "site/sections/Content/SearchTags.tsx": $$$$$$39,
    "site/sections/Content/Table.tsx": $$$$$$40,
    "site/sections/Content/Testimonials.tsx": $$$$$$41,
    "site/sections/Content/TextWithImage.tsx": $$$$$$42,
    "site/sections/Content/TextWithImageHistory.tsx": $$$$$$43,
    "site/sections/Content/UxWriting.tsx": $$$$$$44,
    "site/sections/Footer/Footer.tsx": $$$$$$45,
    "site/sections/Gallery.tsx": $$$$$$47,
    "site/sections/GTM/GTMCustom.tsx": $$$$$$46,
    "site/sections/Images/Banner.tsx": $$$$$$48,
    "site/sections/Images/BannerGrid.tsx": $$$$$$49,
    "site/sections/Images/Carousel.tsx": $$$$$$50,
    "site/sections/Images/ImageGallery.tsx": $$$$$$51,
    "site/sections/Images/LowBannerCarrousel.tsx": $$$$$$52,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$53,
    "site/sections/Institucionals/BannerGridText.tsx": $$$$$$54,
    "site/sections/Institucionals/ButtonNavigation.tsx": $$$$$$55,
    "site/sections/Institucionals/CardsStore.tsx": $$$$$$56,
    "site/sections/Institucionals/LayoutInstitucional.tsx": $$$$$$57,
    "site/sections/Institucionals/Menu.tsx": $$$$$$58,
    "site/sections/Institucionals/RichText.tsx": $$$$$$59,
    "site/sections/Institucionals/RichTextDefault.tsx": $$$$$$60,
    "site/sections/Layout/Container.tsx": $$$$$$63,
    "site/sections/Layout/Flex.tsx": $$$$$$64,
    "site/sections/Layout/Grid.tsx": $$$$$$65,
    "site/sections/Layout/GridItem.tsx": $$$$$$66,
    "site/sections/Links/LinkTree.tsx": $$$$$$67,
    "site/sections/Links/Shortcuts.tsx": $$$$$$68,
    "site/sections/Live/LiveMimo.tsx": $$$$$$69,
    "site/sections/LPs/Marcas.tsx": $$$$$$61,
    "site/sections/LPs/NewsletterPartners.tsx": $$$$$$62,
    "site/sections/meta-tag/meta-tag.tsx": $$$$$$95,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$70,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$71,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$72,
    "site/sections/Modal/Cookies.tsx": $$$$$$73,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$74,
    "site/sections/Oscar/Header.tsx": $$$$$$75,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$76,
    "site/sections/Product/NotFound.tsx": $$$$$$77,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$78,
    "site/sections/Product/ProductDetails.tsx": $$$$$$79,
    "site/sections/Product/ProductInfo.tsx": $$$$$$80,
    "site/sections/Product/ProductShelf.tsx": $$$$$$81,
    "site/sections/Product/ProductShelffWithImage.tsx": $$$$$$84,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$82,
    "site/sections/Product/ProductShelfVisited.tsx": $$$$$$83,
    "site/sections/Product/SearchResult.tsx": $$$$$$85,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$86,
    "site/sections/Product/Wishlist.tsx": $$$$$$87,
    "site/sections/Scripts/Redirect.tsx": $$$$$$90,
    "site/sections/Scripts/Scripts.tsx": $$$$$$91,
    "site/sections/SEO/HeadingTag.tsx": $$$$$$88,
    "site/sections/SEO/SEOPLPV2Custom.tsx": $$$$$$89,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$92,
    "site/sections/Social/WhatsApp.tsx": $$$$$$93,
    "site/sections/Theme/Theme.tsx": $$$$$$94,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
